from src.common.tracker import TrackerCommon


class AlbumerCommon:
    ALBUM_ID = TrackerCommon.ALBUM_ID
    TYPE = 'ALBUM_TYPE'
    GENRE = 'ALBUM_GENRE'
    LABEL = 'ALBUM_LABEL'
    NAME = 'ALBUM_NAME'
    POPULARITY = 'ALBUM_POPULARITY'
    RELEASE_DATE = 'ALBUM_RELEASE_DATE'
    TOTAL_TRACKS = 'ALBUM_TRACK_COUNT'

    SCHEMA = [ALBUM_ID, NAME, TYPE, GENRE, RELEASE_DATE, LABEL, TOTAL_TRACKS, POPULARITY]

    FILE_PATH_PREFIX = 'history/albums/'
