class AlbumerCommon:
    ALBUM_ID = 'ALBUM_ID'
    TYPE = 'ALBUM_TYPE'
    GENRES = 'ALBUM_GENRES'
    LABEL = 'ALBUM_LABEL'
    NAME = 'ALBUM_NAME'
    POPULARITY = 'ALBUM_POPULARITY'
    RELEASE_DATE = 'ALBUM_RELEASE_DATE'
    TOTAL_TRACKS = 'ALBUM_TRACK_COUNT'

    SCHEMA = [ALBUM_ID, NAME, TYPE, GENRES, RELEASE_DATE, LABEL, TOTAL_TRACKS, POPULARITY]

    FILE_PATH_PREFIX = 'history/albums/'
