from src.common.listener import ListenerCommon


class TrackerCommon:
    TRACK_ID = ListenerCommon.TRACK_ID
    ALBUM_ID = 'ALBUM_ID'
    ARTIST_IDS = 'ARTIST_IDS'
    DURATION_MS = ListenerCommon.DURATION
    NAME = 'TRACK_NAME'
    POPULARITY = 'TRACK_POPULARITY'
    EXPLICIT = 'TRACK_EXPLICIT'

    ACOUSTICNESS = 'TRACK_ACOUSTICNESS'
    DANCEABILITY = 'TRACK_DANCEABILITY'
    ENERGY = 'TRACK_ENERGY'
    INSTRUMENTALNESS = 'TRACK_INSTRUMENTALNESS'
    KEY = 'TRACK_KEY'
    LIVENESS = 'TRACK_LIVENESS'
    LOUDNESS = 'TRACK_LOUDNESS'
    MODE = 'TRACK_MODE'
    SPEECHINESS = 'TRACK_SPEECHINESS'
    TEMPO = 'TRACK_TEMPO'
    TIME_SIGNATURE = 'TRACK_TIME_SIGNATURE'
    VALENCE = 'TRACK_VALENCE'

    SCHEMA = [TRACK_ID, NAME, DURATION_MS, ALBUM_ID, ARTIST_IDS, POPULARITY, EXPLICIT,
              ACOUSTICNESS, DANCEABILITY, ENERGY, LIVENESS, LOUDNESS, INSTRUMENTALNESS, SPEECHINESS, VALENCE,
              KEY, MODE, TEMPO, TIME_SIGNATURE]

    FILE_PATH_PREFIX = 'history/tracks/'
